### PR TITLE
Initial support for the ginga viewer as an option

### PR DESCRIPTION
**Pull request by ejeschke**
This adds support for Ginga as an image viewer in the specreduce interidentify GUI tools.

If the user does not have ginga installed or there is a problem importing it then nothing is different from the default.  If the ginga package is installed then the ginga viewer replaces the imageWidget with a ginga-powered one.  This gives you a very full featured image browser.

### CODE REVIEW

**Comment by crawfordsm** [comment]
Thanks so much for the quick pull request @ejeschke !   

I've just tried to check it out and I've run into the error 
  File "test_specred_rss.py", line 9, in <module>
    from specreduce.interidentify import InterIdentify
  File "/Users/crawford/programs/specreduce/specreduce/interidentify.py", line 42, in <module>
    from gingatools import GingaImageDisplay
  File "/Users/crawford/programs/specreduce/specreduce/gingatools.py", line 11, in <module>
    from ginga.qtw.ImageViewCanvasQt import ImageViewCanvas as GingaCanvas
  File "/usr/local/lib/python2.7/site-packages/ginga/qtw/ImageViewCanvasQt.py", line 11, in <module>
    from ginga.qtw import ImageViewQt
  File "/usr/local/lib/python2.7/site-packages/ginga/qtw/ImageViewQt.py", line 15, in <module>
    from ginga.qtw.QtHelp import QtGui, QtCore, QFont, QColor, QImage, \
  File "/usr/local/lib/python2.7/site-packages/ginga/qtw/QtHelp.py", line 50, in <module>
    sip.setapi(cl, 2)
ValueError: API 'QString' has already been set to version 1

Do you know the quick source of this or should I go hunting?

**Comment by ejeschke** [comment]
See the test file and email I sent you.

**Comment by crawfordsm** [comment]
Ah thanks for the update, i'm going to add it here as a note 

    # hack to force Qt v2 api
    import sip
    for cl in ('QString', 'QVariant'):
         sip.setapi(cl, 2)

Is there a way to incorporate this in the code?

**Comment by crawfordsm** [comment]
But, yes, with that I got it to work!  Awesome!

**Comment by crawfordsm** [comment]
If I add that import from sip into the __init__.py it seems to then work without needing it in the script.  Unless there is a good reason not to, can you add that to this pull request and then I'll go ahead and merge it?

**Comment by ejeschke** [comment]
Hi @crawfordsm, I've updated the branch to fix a couple of issues.  First, the layout with the ginga widget now looks good.  I also removed the log messages to stderr.  Checkout the branch and let me know your thoughts.

**Pull request merged**
